### ISSUE TITLE
Proposal Issues

### ISSUE THREAD

**Issue by mfeniseycopes** [Masoule/OVOX#7]
## Timeline
- Looks good!

## Component Hierarchy
- Looks great!
- [x] A component to play pause tracks would be good as we will be able to do this all over (track index item, track show, audioplayer)

## Routes
- [x] User show should use `GET /api/users/:user_id`
- [x] Deleting a comment need not be nested under `track` since we already have a comment id (`DELETE /api/comments/:id`)

## Sample State
- [x] `current_stream` can be its own slice

## Schema
- [x] Images will be handled with the paperclip gem and aws hosting, so we will not be storing a `img_url`, but an `image` with an `attachment` datatype
- [x] Track `likes` should be stored in a join table (joins users to tracks)
- [x] Count of track likes can be calculated from the association

## Wireframes
- Lovely 😃

**Comment by mfeniseycopes** [comment]
Hey @Masoule, here's my feedback. I'll come by and talk to you about it sometime today or tomorrow. Feel free to make the changes and check them off in the meantime.

**Comment by Masoule** [comment]
Thanks Meagan. I made some changes and will do the rest after we talk to make sure I understand them correctly.

**Comment by mfeniseycopes** [comment]
Nice job!
